Recruiting-Your-Club/ryc

.gitignore
build.gradle
src/main/java/com/ryc/api/config/PropertiesConfiguration.java
src/main/java/com/ryc/api/config/SecurityConfiguration.java
src/main/java/com/ryc/api/v1/auth/controller/AuthController.java
src/main/java/com/ryc/api/v1/auth/dto/RegisterRequest.java
src/main/java/com/ryc/api/v1/auth/dto/RegisterResponse.java
src/main/java/com/ryc/api/v1/auth/service/AuthService.java
src/main/java/com/ryc/api/v1/auth/service/AuthServiceImpl.java
src/main/java/com/ryc/api/v1/member/domain/Member.java
src/main/java/com/ryc/api/v1/member/domain/UserRole.java
src/main/java/com/ryc/api/v1/member/repository/MemberRepository.java
src/main/java/com/ryc/api/v1/security/dto/CustomUserDetail.java
src/main/java/com/ryc/api/v1/security/exceptions/RestAuthenticationEntryPoint.java
src/main/java/com/ryc/api/v1/security/exceptions/TokenAccessDeniedHandler.java
src/main/java/com/ryc/api/v1/security/filter/EmailPasswordAuthenticationFilter.java
src/main/java/com/ryc/api/v1/security/filter/JwtAuthenticationFilter.java
src/main/java/com/ryc/api/v1/security/jwt/JwtProperties.java
src/main/java/com/ryc/api/v1/security/jwt/JwtTokenManager.java
src/main/java/com/ryc/api/v1/security/service/CustomUserDetailsService.java

Spring Security 설정 및 로그인 회원가입 로직 구현
구현 주요 사항
1. EmailPasswordAuthenticationFilter :  UsernamePasswordAuthenticationFilter를 커스텀하여 로그인 로직 구현 및 로그인 성공시 JWT 토큰 발행
2. Auth0-java-jwt 라이브러리를 이용하여 JWT 토큰 발행

Spring Security 초기 설정 및 로그인 회원가입 구현

---

.github/issue-branch.yml
.github/workflows/create-issue-branch.yml

robvanderleek/create-issue-branch를 이용하여, 이슈 생성 후 assigned시 브랜치 자동 생성 설정 구현
참고링크 
https://github.com/robvanderleek/create-issue-branch

chore: 이슈 생성 후 브랜치 생성 자동화 설정 완료

---

.github/ISSUE_TEMPLATE/bug-issue.md
.github/ISSUE_TEMPLATE/docs-issue.md
.github/ISSUE_TEMPLATE/feature-issue.md
.github/ISSUE_TEMPLATE/infra-issue.md
.github/ISSUE_TEMPLATE/refactor-issue.md
.github/ISSUE_TEMPLATE/test-issue.md

.github 폴더 수정
이슈 템플릿 수정 및 레포지토리 환경 설정 내용 main 반영

[ALL] 모노 레포지토리 통합으로 인한, 레포지토리 설정 main 브랜치에 반영

---

client/src/components/Footer/Footer.style.ts
client/src/components/Footer/Footer.tsx
client/src/pages/TestPage/index.tsx

`closed #186 `
breakpoint가 생성되었기에 장치마다 다른 Footer 화면을 구성했습니다. 디자인적으로 괜찮은 지 피드백 주시면 감사하겠습니다!
a태그에 mailto 기능을 이용해서 Footer에 메일 주소 클릭 시 메일을 보낼 수 있게 하는 임시 기능을 생성했습니다!
- 리뷰 포인트
추정 시간: 2시간
실제 시간:  2시간

[REFACTOR/FE] Footer 리팩토링

---

client/src/hooks/components/useFilteredFile.tsx

`closed #204 `
constants 파일 수정하고 머지 시 hook 파일에 있는 import 경로를 못 봐서 수정했습니다. 
추정 시간:   
실제 시간:

[REFACTOR/FE] FileUpLoader import 경로 수정

---

server/src/main/java/com/ryc/api/config/WebConfig.java
server/src/main/java/com/ryc/api/v2/admin/infra/entity/AdminEntity.java
server/src/main/java/com/ryc/api/v2/club/infra/entity/ClubEntity.java
server/src/main/java/com/ryc/api/v2/common/aop/aspect/ClubAspect.java

[BE] CORS 설정 및 image URL에 대한 DB 자료형 변경

---

server/src/main/java/com/ryc/api/config/WebConfig.java
server/src/main/java/com/ryc/api/v2/email/application/EmailService.java

Fix: allowOrigins

---

server/src/main/java/com/ryc/api/v2/admin/presentation/AdminController.java
server/src/main/java/com/ryc/api/v2/admin/presentation/AdminHttpApi.java
server/src/main/java/com/ryc/api/v2/admin/presentation/response/AdminEmailDuplicatedResponse.java
server/src/main/java/com/ryc/api/v2/admin/service/AdminService.java
server/src/main/java/com/ryc/api/v2/common/exception/GlobalExceptionHandler.java

[BE] 회원가입 시 이메일 중복 확인 API 

---

server/src/main/java/com/ryc/api/v2/applicant/domain/Applicant.java
server/src/main/java/com/ryc/api/v2/applicant/domain/ApplicantRepository.java
server/src/main/java/com/ryc/api/v2/applicant/domain/enums/ApplicantStatus.java
server/src/main/java/com/ryc/api/v2/applicant/infra/ApplicantRepositoryImpl.java
server/src/main/java/com/ryc/api/v2/applicant/infra/entity/ApplicantEntity.java
server/src/main/java/com/ryc/api/v2/applicant/infra/jpa/ApplicantJpaRepository.java
server/src/main/java/com/ryc/api/v2/applicant/infra/mapper/ApplicantMapper.java
server/src/main/java/com/ryc/api/v2/application/domain/Answer.java
server/src/main/java/com/ryc/api/v2/application/domain/AnswerChoice.java
server/src/main/java/com/ryc/api/v2/application/domain/Application.java
server/src/main/java/com/ryc/api/v2/application/domain/ApplicationRepository.java
server/src/main/java/com/ryc/api/v2/application/infra/ApplicationRepositoryImpl.java
server/src/main/java/com/ryc/api/v2/application/infra/entity/AnswerChoiceEntity.java
server/src/main/java/com/ryc/api/v2/application/infra/entity/AnswerEntity.java
server/src/main/java/com/ryc/api/v2/application/infra/entity/ApplicationEntity.java
server/src/main/java/com/ryc/api/v2/application/infra/jpa/AnswerChoiceJpaRepository.java
server/src/main/java/com/ryc/api/v2/application/infra/jpa/AnswerJpaRepository.java
server/src/main/java/com/ryc/api/v2/application/infra/jpa/ApplicationJpaRepository.java
server/src/main/java/com/ryc/api/v2/application/infra/mapper/AnswerChoiceMapper.java
server/src/main/java/com/ryc/api/v2/application/infra/mapper/AnswerMapper.java
server/src/main/java/com/ryc/api/v2/application/infra/mapper/ApplicationMapper.java

#231 
해당 도메인들의 ERD입니다.
- 리뷰 포인트
추정 시간:   
실제 시간:   

[BE] 지원 도메인 영속성 계층 구현 

---

server/src/main/java/com/ryc/api/v2/club/service/ClubService.java

#405 
- 리뷰 포인트
추정 시간:   10분
실제 시간:   10분

[BE] club 조회 Response 빌더 누락 필드값 추가

---

monorepo/apps/admin/src/api/domain/auth/auth.ts
monorepo/apps/admin/src/api/domain/auth/types.ts
monorepo/apps/admin/src/api/domain/club/types.ts
monorepo/apps/admin/src/components/MainCardEditDialog/MainCardEditDialog.tsx
monorepo/apps/admin/src/components/SideBar/SideBar.tsx
monorepo/apps/admin/src/pages/AuthPage/RegisterPage/RegisterPage.tsx
monorepo/apps/admin/src/pages/ClubCreatePage/ClubCreatePage.tsx
monorepo/apps/admin/src/pages/ClubEditPage/ClubEditPage.tsx
monorepo/apps/admin/src/pages/TestPage/index.tsx

`closed #413 `
추정 시간:   2시간
실제 시간:   2시간

[FE/HOTFIX] 클라이언트 오류 수정

---

monorepo/apps/admin/src/components/SideBar/SideBar.style.tsx
monorepo/apps/admin/src/components/SideBar/SideBar.tsx
monorepo/apps/admin/src/pages/TestPage/index.tsx
monorepo/apps/user/src/utils/parseAnnouncementData.ts
monorepo/packages/ui/src/components/Dropdown/Dropdown.styles.ts
monorepo/packages/ui/src/components/Tooltip/Tooltip.style.ts
monorepo/packages/ui/src/components/Tooltip/Tooltip.tsx
monorepo/packages/ui/src/components/Tooltip/TooltipPortal.tsx
monorepo/packages/ui/src/components/Tooltip/types.ts

`closed #412 `
Tooltip 리팩토링 및 전체적인 페이지 버그 수정을 진행했습니다.
추정 시간: 7시간
실제 시간: 7시간

[FE] user, admin 페이지 버그 수정 및 Tooltip 리팩토링

---

monorepo/packages/ui/src/components/Editor/utils/selection.ts

`closed #419 `
추정 시간:   30분
실제 시간:   40분

[FE] Editor px값 변경되는 오류 수정

---

monorepo/apps/admin/src/components/SideBar/SideBar.style.tsx
monorepo/apps/admin/src/components/SideBar/SideBar.tsx

`closed #422 `
추정 시간: 1시간
실제 시간:  1시간

[FE] 사이드바 드랍다운 버그 수정

---

server/src/main/java/com/ryc/api/v2/announcement/service/AnnouncementService.java
server/src/main/java/com/ryc/api/v2/applicant/service/ApplicantService.java
server/src/main/java/com/ryc/api/v2/auth/service/AuthService.java
server/src/main/java/com/ryc/api/v2/email/service/EmailService.java
server/src/main/java/com/ryc/api/v2/evaluation/service/EvaluationService.java
server/src/main/java/com/ryc/api/v2/interview/service/InterviewService.java
server/src/main/java/com/ryc/api/v2/role/service/ClubRoleService.java

ransactionalEventListener과 Transactional 혼용 버그 수정

---

monorepo/packages/ui/src/components/Editor/EditorTextarea.tsx

`closed #452 `
추정 시간:  1시간
실제 시간:  1시간

[FE] 관리자 페이지 Editor style 적용 안되는 오류 수정

---

server/src/main/java/com/ryc/api/ApiApplication.java

[BE/HOTFIX] JVM 어플리케이션 한국 시간대로 강제

---

monorepo/apps/user/src/pages/ClubDetailPage/RecruitmentPage/RecruitmentPage.tsx
monorepo/apps/user/src/utils/parseAnnouncementData.ts

ex) `closed #471 `
추정 시간:  20분
실제 시간:   20분

[FE/HOTFIX] 기한 null에 대한 처리 수정

---

server/src/main/java/com/ryc/api/config/SwaggerConfiguration.java
server/src/main/java/com/ryc/api/v2/announcement/presentation/dto/response/AnnouncementGetDetailResponse.java

[BE] 공고 상세 조회 API에 응답 값 추가 

---

monorepo/apps/user/src/pages/ClubApplyPage/ClubApplyPage.tsx
monorepo/apps/user/src/pages/ClubApplyPage/DetailQuestionPage/ClubApplyDetailQuestionPage.tsx

ex) `closed #494 `
추정 시간:  30분
실제 시간:  30분

[FE/HOTFIX] 지원서 동일 질문 입력 안되는 버그 수정

---

monorepo/apps/admin/src/components/DatePicker/DatePicker.tsx
monorepo/apps/admin/src/components/FileDownloader/FileDownloader.tsx
monorepo/apps/admin/src/pages/AuthPage/RegisterPage/RegisterPage.tsx
monorepo/apps/admin/src/pages/RecruitCreatePage/PreviewStep/PreviewStep.tsx
monorepo/apps/admin/src/pages/RecruitCreatePage/buildAnnouncementSubmitRequest.ts

`closed #502 `
추정 시간: 5분  
실제 시간:  5분

[FE] 상시모집 날짜 및 다운로더 오류 수정, 비밀번호 제약 변경

---

server/src/main/java/com/ryc/api/v2/application/service/ApplicationService.java
server/src/main/java/com/ryc/api/v2/email/domain/event/ApplicationSuccessEmailEvent.java
server/src/main/java/com/ryc/api/v2/email/service/EmailService.java
server/src/main/resources/templates/application-submitted.html

PR과 연관된 이슈의 번호를 작성해주세요.
PR 머지 시 close 되어야 하는 이슈의 경우 이슈 번호 앞에 `closed` 키워드를 붙여주세요.  
ex) `closed #2`
리뷰시 중점적으로 봐주었으면 좋을 부분을 적어주세요.  
없다면 적지 않아도 됩니다.  
- 리뷰 포인트
추정 시간:   
실제 시간:   

[BE] 지원시 clubName 명시되게 변경

---

monorepo/apps/admin/src/pages/ClubMemberRolePage/ClubMemberRolePage.tsx
monorepo/apps/user/src/pages/ClubApplyPage/ClubApplyPage.tsx
monorepo/packages/ui/src/components/FileUpLoader/FileUpLoader.style.ts
monorepo/packages/ui/src/components/FileUpLoader/FileUpLoaderItem.tsx

ex) `closed #505 `
추정 시간: 2시간
실제 시간: 2시간

[FE/HOTFIX] 사용자 권한 설정 페이지 버그 수정

---

monorepo/apps/user/src/router.tsx

closed #513 
면접 예약 페이지 router 수정

[FE/HOTFIX] 면접 예약 페이지 rotuer 수정

---

monorepo/apps/admin/src/pages/AnnouncementPage/RecruitmenPage/RecruitmentPage.tsx
monorepo/apps/admin/src/pages/RecruitEditPage/RecruitEditPage.tsx

`closed #516 `
추정 시간:  10분
실제 시간:  10분

[FE/HOTFIX] 상시모집 날짜 이상하게 나오는 현상 해결

---

server/src/main/java/com/ryc/api/v2/announcement/domain/AnnouncementValidator.java
server/src/main/java/com/ryc/api/v2/announcement/presentation/dto/request/AnnouncementUpdateRequest.java
server/src/main/java/com/ryc/api/v2/club/domain/ClubValidator.java
server/src/main/java/com/ryc/api/v2/club/presentation/dto/request/ClubUpdateRequest.java
server/src/main/java/com/ryc/api/v2/common/exception/code/InvalidFormatErrorCode.java

[BE] 동아리 상세 설명 제한 길이 증대 

---

monorepo/apps/user/src/utils/parseAnnouncementData.ts

ex) `closed #525 `
추정 시간: 10분
실제 시간: 10분

[FE/HOTFIX] 프론트 버그 수정

---

monorepo/apps/admin/src/components/CardBox/CardBox.tsx
monorepo/apps/admin/src/components/InterviewSettingDialog/InterviewSettingDialog.tsx
monorepo/apps/admin/src/components/InterviewSettingDialog/types.ts
monorepo/apps/admin/src/components/InterviewTimeBox/InterviewTimeBox.style.ts
monorepo/apps/admin/src/components/InterviewTimeBox/InterviewTimeBox.tsx
monorepo/apps/admin/src/components/PlainEmailDialog/PlainEmailDialog.tsx
monorepo/apps/admin/src/components/PlainEmailDialog/types.ts
monorepo/apps/admin/src/pages/StepManagementPage/StepManagementPage.tsx
monorepo/apps/admin/src/pages/TestPage/index.tsx
monorepo/apps/user/src/api/domain/club/types.ts
monorepo/apps/user/src/pages/ReservationPage/ReservationPage.tsx

`closed #531 `
추정 시간:  1시간
실제 시간:  1시간

[FE] 타입 오류 해결 및 사용자 고려하여 UI 변경

---

.github/workflows/front-deploy.yml
monorepo/apps/admin/webpack.prod.js
monorepo/apps/user/webpack.prod.js

`closed #535`
sentry로 인해 깃허브 액션 빌드 단계에서 발생하는 오류 수정

[FE/HOTFIX] 깃허브 액션 오류 수정

---

monorepo/apps/admin/public/index.html
monorepo/apps/admin/src/pages/AnnouncementPage/RecruitmenPage/RecruitmentPage.tsx
monorepo/apps/user/public/index.html
monorepo/apps/user/src/utils/parseAnnouncementData.ts

ex) `closed #560 `
추정 시간: 10분
실제 시간:  10분

[FE/HOTFIX] 프론트 공고 요약 버그 수정

---

server/src/main/java/com/ryc/api/v2/interview/domain/InterviewRepository.java
server/src/main/java/com/ryc/api/v2/interview/infra/InterviewRepositoryImpl.java
server/src/main/java/com/ryc/api/v2/interview/infra/jpa/InterviewSlotJpaRepository.java
server/src/main/java/com/ryc/api/v2/interview/service/InterviewReminderService.java

[BE] entity와 JPQL 간의 필드 이름 불일치 해결
